# Generated by Django 3.2.10 on 2024-01-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraissue',
            name='actual_hours',
            field=models.IntegerField(default=0, help_text='实际工时', verbose_name='实际工时'),
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='expected_hours',
            field=models.IntegerField(default=0, help_text='预期工时', verbose_name='预期工时'),
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='pending_datetime',
            field=models.DateTimeField(blank=True, help_text='开始处理时间', null=True, verbose_name='开始处理时间'),
        ),
    ]
